// screens.dart
export 'package:gd_youth_talk/src/presentation/splash/splash_screen.dart';
export 'package:gd_youth_talk/src/presentation/landing/landing_screen.dart';
export 'package:gd_youth_talk/src/presentation/main/main_screen.dart';
export 'package:gd_youth_talk/src/presentation/home/home_screen.dart';
export 'package:gd_youth_talk/src/presentation/search/search_screen.dart';
export 'package:gd_youth_talk/src/presentation/calendar/calendar_screen.dart';
export 'package:gd_youth_talk/src/presentation/more/more_screen.dart';
export 'package:gd_youth_talk/src/presentation/more/theme_screen.dart';
export 'package:gd_youth_talk/src/presentation/web/webview_screen.dart';
export 'package:gd_youth_talk/src/presentation/detail/detail_screen.dart';
export 'package:gd_youth_talk/src/presentation/category/category_screen.dart';
