name: gd_youth_talk
description: "A youth information app providing real-time updates on programs and services from the Gangdong-gu Youth Center"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 상태괸리
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^3.8.1

  # Local Storage
  shared_preferences: ^2.3.3

  # Networking
  dio: ^5.7.0

  # UI
  intl: ^0.19.0
  table_calendar: ^3.1.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

  # Web
  flutter_inappwebview: ^6.1.5

  # Shared
  share_plus: ^10.1.2
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#  assets:
#    - assets/

flutter:
  uses-material-design: true
